import pickle
from .math import lognormal


def sample_gen(mean=1, std=1, n=100, filename=None):
    """simple lognormal sample generator, can be exported or return to memory"""
    sample = lognormal(mean, std, n)
    if filename is not None:
        with open(f"./{filename}", 'wb') as f:
            pickle.dump(sample, f)
    else:
        return sample


def sample_gen_group(samplenumber_list=(100,)):
    """macro sample generation of different number of sample"""
    for _ in samplenumber_list:
        sample_gen(mean=1, std=1, n=_, filename=f"premade_lognormal_sample_pop{_}.sample")


def sample_load(filename):
    """load sample file generated by sample_gen function"""
    with open(f"./{filename}", 'rb') as f:
        x = pickle.load(f)
    return x